name: CI

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '**.md'

permissions:
  contents: read

jobs:

  Test-Shell-P19:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:

      - name: Checkout P19 repo
        uses: actions/checkout@v3

      - name: Set up Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: "3.8"
          cache: "pip"
          
      - name: Install Dependencies and Set up Environment
        run: |
          pip install -r requirements.txt

      - name: Run Unit Tests
        run: |
          python -m unittest discover test/
          
      - name: Check Coverage
        run: |
          coverage run  --source=src -m unittest discover
          coverage report --fail-under=95

      - name: Run System Tests
        run: |
          #docker build -t shell .
          docker build -t comp0010-system-test .
          python system_test/tests.py -v
          
        
