name: CI

on:
  workflow_dispatch:
  push:
    branches:
      master
    paths-ignore:
      - '**.md'

permissions:
  contents: read

jobs:

  Test-Shell-P19:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:

      - name: Checkout P19 repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: "3.8"
          cache: "pip"
          
      - name: Install Dependencies and Set up Environment
        run: |
          #pip install -r requirements.txt
          pip install parameterized
          pip install hypothesis
          export PYTHONPATH="${PYTHONPATH}:${{ github.workspace }}"
          

      - name: Run Unit Tests
        run: python -m unittest discover test/
